### ISSUE TITLE
DataGridView disappears after several minutes inactivity.

### ISSUE THREAD

**Issue by trainee9876** [nsi-test/UnlockADUsers#1]
After starting the program and several minutes inactivity DataGridView disappears - looks as if doesn't exist. (Blank). It happens if it is started as exe and via powershell too. Very annoying.

**Comment by nsi-test** [comment]
There was a bug concerning the Resize event handler - arbitrary zeroizing the form size, which affected the new size of DataGridView. Excluding zero sizes added in logic. It should be fixed in the new release:
[https://github.com/nsi-test/UnlockADUsers/releases/tag/1.4.1](url)

**Comment by nsi-test** [comment]
See the last post.
